### ISSUE TITLE
Clicking on ayah number badge causes bug (Read comment for details)

### ISSUE THREAD

**Issue by Brumo21** [quran/quran.com-frontend-v2#280]
When you open a surah, clicking on the ayah number badge will cause any subsequent clicks on the other arabic words to play no sound, it warrants a refresh of the page to reset it.

[Ayah Number Badge Image](https://imgur.com/a/nH7UZoO)

**Comment by hahasuperking** [comment]
Working on the issue, and this is the history of discussion:
`Ismeal  7:11 PM
inshAllah, thanks, I just would like to confirm before fixing the bug, so when click “Ayah number”, is it expected to play the sound of the Ayah?
white_check_mark
eyes
raised_hands





7:11
Or just show the Ayah number with a hint message?
7:13
Screen Shot 2020-11-25 at 7.12.45 PM.png 
Screen Shot 2020-11-25 at 7.12.45 PM.png


7:13
Ayah number -> I mean the last icon in above screenshot :slightly_smiling_face:

Naveed  7:17 PM
we’re playing word audio when user click on word. I guess he is saying playing word audio stopped after clicking on last word( that is ayah number)

Ismeal  7:18 PM
Yep, I can reproduce that problem, I tried to use chrome debug the issue, I found that clicking “ayah number” trigger the same function “play” which should be only triggered by clicking word
7:18
So I am thinking perhaps we should avoid calling play when click “Ayah number”

Naveed  7:19 PM
yeah because last word don’t have audio, same is for “pause marks”.
7:19
fix is simple, just check the “word type” before playing the audio. word type should be “word” we’ll skip other word types

Ismeal  7:19 PM
Got it, thanks
7:20
I will add the fix and let you review
7:20
Forgive me if my fixing is ugly, but I will try my best

Naveed  7:21 PM
or you can just check word has “audio” data
7:21
<span class="end w" id="w-8420" data-local="english" data-audio="" data-t="Ayah 7" data-tr="" data-position="10" data-key="" data-controller="word" data-original-title="" title="">
  <span class="p1-uthmani uthmani" data-original-title="" title="">
    ٧
  </span>
</span>
data-audio=“”  is blank for this word, we don’t play this word.

Ismeal  7:21 PM
Yep, “Ayah” should have no data, so we can skip
7:22
The second way may be extensible!

Naveed  7:23 PM
I believe checking data-audio is best solution. We might add tajweed audio soon. Tajweed audio is usually audio of multiple words.

Ismeal  7:23 PM
I agree with you, check data-audio is empty should be better and secure

Naveed  7:24 PM
https://github.com/quran/quran.com-frontend-v2/blob/master/app/javascript/controllers/word_controller.js#L60
GitHubGitHub
quran/quran.com-frontend-v2
Contribute to quran/quran.com-frontend-v2 development by creating an account on GitHub.

Ismeal  7:24 PM
We should check data.audio before calling pay, agree?

Naveed  7:24 PM
`if (player && data.audio?.length > 0)`
should fix this inshAllah (edited) 

Ismeal  7:25 PM
:+1:`
