### ISSUE TITLE
Wrong text rendering when "Uthmani Text" or "Tajweed Text" is selected

### ISSUE THREAD

**Issue by YousufSohail** [quran/quran.com-frontend-v2#289]
Please see attached screenshots:

<img width="1436" alt="Screenshot 2020-12-15 at 8 52 42 PM" src="https://user-images.githubusercontent.com/2059838/102326338-1d157a80-3fa6-11eb-8136-bdaf6f61a1d7.png">

<img width="1432" alt="Screenshot 2020-12-15 at 8 52 27 PM" src="https://user-images.githubusercontent.com/2059838/102326360-2272c500-3fa6-11eb-9fcb-df13552c8545.png">

**Comment by aboqasem** [comment]
Assalamualaykum, Jazakumullahu Khairan, this is my first time here and my first time dealing Ruby, Rails, and Postgres.

I was trying to debug this issue, and I checked on the database by comparing both **(Alif-Lãm-Mĩm)**s form **Ali 'Imran** and **AL-Baqarah** chapters, I executed:
```sql
SELECT * FROM quran.verses
WHERE chapter_id = 2 AND verse_number = 1
```
then
```sql
SELECT * FROM quran.verses
WHERE chapter_id = 3 AND verse_number = 1
```
The comparison looks clean:

<img width="1061" alt="diff" src="https://user-images.githubusercontent.com/62098043/102444562-75ab4d00-4064-11eb-81a1-3c87ed1861df.png">

So I think the problem is not caused by the database, still learning Rails and debugging...

**Comment by YousufSohail** [comment]
@aboqasem how can I access db?

**Comment by aboqasem** [comment]
Just follow the [instructions](https://github.com/quran/quran.com-frontend-v2#set-up) for setting up the project locally, then use [pgAdmin](https://www.pgadmin.org/download/) to run the queries.

**Comment by benomaire** [comment]
probably the problem is with "Uthmani Text" alone. 

1. In translation mode, "Tajweed Text" is correct, _and colored, as expected!_
2. In reading mode, "Tajweed Text" looks exactly like "Uthmani Text". [Screenshots above](https://github.com/quran/quran.com-frontend-v2/issues/289#issue-768599475)


<details><summary>Screenshots for translation mode</summary>

"Uthmani Text":
![img2](https://user-images.githubusercontent.com/69304392/102491397-2aebfe00-4081-11eb-8551-adf274befdb5.png)

"Tajweed Text":
![img1](https://user-images.githubusercontent.com/69304392/102491391-29223a80-4081-11eb-8211-b8bb78ab3be8.png)

</details>

**Comment by naveed-ahmad** [comment]
Salam everyone, fixed this on beta.quran.com will be pushed live in few days inshAllah.

**Comment by benomaire** [comment]
جزاكم الله خيرا
But still "Tajweed Text" and "Uthmani Text" are the same in reading mode.

**Comment by naveed-ahmad** [comment]
That's intentional. In reading more we are showing word-by-word text and we don't have wbw tajweed text yet.
