### ISSUE TITLE
[62;3] Missing correct translation of the word مِّنْهُمْ (On touch). Please, add the right translation "from them".

### ISSUE THREAD

**Issue by hopeful33** [quran/quran.com-frontend-v2#365]
[Al-Jumah, 3]Highly Dangerous translation error, That maybe Outstretched wrong translation Fitnah.

The error is present, this verse On touch translation, https://Quran.com/62/3/ The word meaning of مِّنْهُمْ is wrongly present "among them".  But Can i ask, Isn't it "from them"?
![Screenshot_20210331-230913](https://user-images.githubusercontent.com/81706588/113185946-df004600-9278-11eb-920f-1c28a3b526bc.png)

Allah says,
"And not mix the truth with falsehood and conceal the truth while you know." [Surah Baqarah, verse 42, Word by word translation]

Hi Brother, 
By the grace of All-mighty Allah, I found a dangerous translation error. 

Maybe you know, The Arabic word "fīkum
فِيكُمْ" means 
"among you"

Right? 

I Checked, Verse number 7 of Surah Hujurat, It’s ok.

And 

The word "min
مِّنْ" refers "From

I'm right? 

In the verse number 2 of Surah Al-Jumu'ah, the word "min'hum
مِّنْهُمْ" translated  
"from themselves".

Agree?

But, in the verse number 3 of Surah Al-Jumu'ah, The same word "min'hum
مِّنْهُمْ" is translated 
"Among them".

Which are directly wrong. Any doubt? Please, Change the meaning to the " from them". [62;3]

I know, You guys doing Appreciateful job. Allah Bless you. 

Brother, 
If you think about it neutral perspective, 

Is it not a confusing error?  Please, for get mercy from Allah, fix this error as soon as possible. 

I tell it because, 
"Indeed, those who conceal the clear proofs, evidences and the guidance, which We have sent down, after We have made it clear for the People in the Book, they are the ones cursed by Allah and cursed by the cursers." [quran.com/2/42]

A Hadith in the Musnad, narrated through several chains of narrators, that strengthens the overall judgment of the Hadith, states that Abu Hurayrah narrated that Allah's Messenger said;

مَنْ سُيِلَ عَنْ عِلْمٍ فَكَتَمَهُ أُلْجِمَ يَوْمَ الْقِيَامَةِ بِلِجَامٍ مِنْ نَار

Whoever was asked about knowledge that one has, but he hid it, then a bridle made of fire will be tied around his mouth on the Day of Resurrection.
[From, https://qurano.com/en/2-al-baqara/verse-159/]

**Comment by benomaire** [comment]
Thank you for the report!
few points:
1. In Arabic, there is no single meaning for "مِن".
2. Translation, generally, is not done literally. I mean, there is no one-to-one mapping for every word in both source and destination languages (ignoring the context). Otherwise, anyone could look up a dictionary and translate. In fact, decent dictionaries usually list multiple meanings.
3. Let's focus on the Ayah you quoted; Have you read the available translations? Currently, there are about 14 English translations of the meanings of the Quran on Quran.com. To show them,
a) go to `settings` (the icon in the top-right corner)
b) go to `choose translations`.
c) check all the English translations.
I suggest you read them, then decide whether "among them" or "from them" fit more.
4. Checkout the meanings of "from" and "among" in a dictionary.
5. To further clarify the meaning of the Ayah, you can read the Tafasir by touching the `Tafsirs` icon below the Ayah.
6. If I am not mistaken, the current "among them" is coming from the translation by "Muhammad Taqi-ud-Din al-Hilali & Muhammad Muhsin Khan", which is the translation [currently printed by King Fahd Glorious Quran Printing Complex](https://qurancomplex.gov.sa/kfgqpc-quran-translate-english/) after careful consideration of some other translations.
7. There is no issue in Arabic if you have other sentences with "فِيكُم" get translated to "among you".
8. I don't think it is a **dangerous** error. I also don't agree with you that "among them" is not acceptable here.
9. If you read till here, then I can probably encourage you to continue learning Arabic. You can do it! Then you won't need to read translations.
والله أعلم
جزاكم الله خيرا

**Comment by hoopoe1427** [comment]
According to the Arabic Corpus online, the translation in Quran.com does appear correct
(62:3:2)
min'hum
among them
here is the URL:
https://corpus.quran.com/wordbyword.jsp?chapter=62&verse=3
scroll down to get to it
The Arabic Corpus is an annotated and trusted source

**Comment by hopeful33** [comment]
Hi,
Jajakalla Kairan. ALLAH BLESS YOU FOR YOUR Details Email and kind word.
Thank you so much for encourage me for learning Arabic.

Can you suggest me some Credible dictionary, that you personally trust?

Aalayhi Oua Sallam.
