### ISSUE TITLE
Advanced Copy is removed

### ISSUE THREAD

**Issue by rizdubai** [quran/quran.com-frontend-v2#496]
I am very disappointed to see Advanced copy removed from quran.com. It has affected my research as I used to use this feature very much from quran.com. Request you to reinstate this very useful feature as soon as possible

**Comment by REDDDDY** [comment]
> 
> 
> I am very disappointed to see Advanced copy removed from quran.com. It has affected my research as I used to use this feature very much from quran.com. Request you to reinstate this very useful feature as soon as possible



Assalamualaikum devs.

Subject :Recent update has caused missing feature

I always come here to quran.com for reference and do some advanced text copy but for some reason
it is no longer giving this options. What is going on?
I need to use this feature so that I can super copy all the different texts from different languages
for my videos. Please fix this.
Thank you.

Missing : Advanced Copy feature

**Comment by REDDDDY** [comment]
RizDubai. You can come and join the developer's discord channel using the link below. I'm already there 

https://discord.gg/FxRWSBfWxn
