### ISSUE TITLE
Not using React JS?

### ISSUE THREAD

**Issue by ahsanghalib** [quran/quran.com-frontend-v2#54]
Hello, I am little curious that previous version is with React SSR but in current you are not using react? Why?

**Comment by naveed-ahmad** [comment]
Yeah had to move to rails because there was almost no contribution on reactjs project. V2 is developing using rails, SSR rendering and stimulusjs on frontend. 

For some reason, performance of rails app seems much better than reactjs. We'll see the final results once rails app is deployed to production.
