### ISSUE TITLE
حذف التعليقات الهامشية بالكامل - Disregarding footnotes as a whole

### ISSUE THREAD

**Issue by mahmoudelramly** [quran/quran.com-frontend-v2#540]
السلام عليكم
جزاكم الله خيراً على المجهود الرائع ورزقكم الإخلاص وجعله في ميزان حسناتكم

تُعَرِفون هذا الموقع بأنه [مجرد أداة](https://www.quran.com/support) :
`Quran.com is an online reading, listening and studying tool.`

أرى أن بعض الترجمات بها هوامش لتعليق المترجم
وما لفت نظري هو [الآية 46 من سورة الحج](https://quran.com/22:46) :
و ترجمة معينة بها هامش وتعليق :
```
Have they not journeyed in the land that their hearts might understand and their ears might listen? For indeed it is not the eyes that are blinded;1 it is rather the hearts in the breasts that are rendered blind.
— Tafheem-ul-Quran - Abul Ala Maududi
```

```
Footnote
The words “blinded are the hearts” have been used in the metaphorical and not in the literal sense. Since the heart is regarded as the center of emotions, feelings and of mental and moral qualities, these words have been used to imply that their obduracy has inhibited them from feeling and acting rationally.
```

و لكن مؤخراً بعد تعلم الإنسان ما لم يعلم ، [هناك أبحاث علمية ظهرت قبل عام 2000](https://www.youtube.com/watch?v=LelkiUDS0yM) ، تثبت أن ما جاء في تلك الآية ليس مجازاً بل حرفي من خالق كل شيء سبحانه وتعالى.
هذه الأبحاث لم تلق الإنتشار الكافي بعد ، ولم تصل إلى مرحلة أن جميع الأطباء أقروا بها وقاموا بدراستها وتدريسها ، فسبحان القائل  [`وَمَا أُوتِيتُمْ مِنَ الْعِلْمِ إِلَّا قَلِيلًا`](https://quran.com/17:85)

والمترجم رحمه الله [توفي في 1979](https://en.wikipedia.org/wiki/Abul_A%27la_Maududi)

بعض التعليقات تحوي بيان لأحكام وروابط لأيات متعلقة [مثل هذه الآية](https://quran.com/2:219) وهي مفيدة لكن ليس في هذا السياق وفي المصاحف العربية الخالصة لا توجد مثل هذه التعليقات، فإن أردتم فيفضل ألا يخالط كلام الله تعليقات البشر في موقع القرآن الرئيسي، معلوم أن ترجمات المعاني هي إجتهاد بشري وقد تختلف حسب فهم المترجم وقابلية اللغة المترجم إليها لنقل المعنى لكن التعليق على الآيات أمر مختلف ، أرجو أن تكون هذه النقطة واضحة

لذا أقترح حذف كل التعليقات الهامشية من الترجمات ليظل فقط نص ترجمة المعاني وربما إن يسر الله لكم ، إنشاء موقع منفصل للتفاسير ، مع ملحوظة كبيرة في الأعلى مثل :
`هذه التفاسير هي إجتهاد بشر ، بما تيسر لهم من علم زمانهم وعلمهم باللغة العربية، وإنما هذا الكتاب لا يَعْوَجُّ فيقومُ ولا يزيغُ فيستعتبُ ولا تَنقضي عجائبُه ولا يخلقُ من كثرةِ الرَدِّ و لاَ يَشْبَعُ مِنْهُ الْعُلَمَاءُ`

مقتبس من [حديث شريف أغلب رواياته ضعيفة](https://dorar.net/hadith/search?q=+%D8%AA%D9%86%D9%82%D8%B6%D9%8A+%D8%B9%D8%AC%D8%A7%D8%A6%D8%A8%D9%87&st=w&xclude=&rawi%5B%5D=)

[رواية لا بأس بها](https://dorar.net/h/0400571d26e560778b751e0cb0378da7)

قال رسول الله صلى الله عليه وسلم
`إنَّ هذا القرآنَ مَأْدُبَةُ اللهِ فتَعَلَّموا مَأْدُبَتَه ما استطعتم وإنَّ هذا القرآنَ هو حبلُ اللهِ وهو النورُ المبينُ والشفاءُ النافعُ عِصْمَةُ مَن تَمَسَّك به ونجاةُ مَن تَبِعَه لا يَعْوَجُّ فيُقَوَّمُ ولا يَزِيغُ فيُسْتَعْتَبُ ولا تَنْقَضِي عجائبُه ولا يَخْلَقُ عن كَثْرَةِ الرَّدِّ اتلُوه فإنَّ اللهَ يأجرُكم على تلاوتِه بكلِّ حرفٍ عَشْرُ حسناتٍ أَمَا إني لا أقول ب الم حَرْفٌ ولكن بالألفِ عَشْرًا وباللامِ عَشْرًا وبالميمِ عَشْرًا`

[والنسخة المترجمة](https://sunnah.com/tirmidhi:2906)

بارك الله فيكم وفي ذرياتكم

Please remove all footnotes not to mix God words with human comments so that Quran.com would be like an Arabic Mushaf pure without any human comments
and may be make a separate website for elaboration and commentary with a note on the top
`these commentaries are a human effort done with the knowledge they had at their time , and their knowledge of Arabic language,  But this is a book that scholars can never have enough of it, and it shall not become dull from reciting it much, and the amazement of it does not diminish. `

God bless you all.

**Comment by Haxsen** [comment]
In my humble opinion, the footnotes are well-done. They should be kept (must) because people misquote the verses (haters of Islam). The footnotes are helpful for the new reader, whom the haters might send to misquote. For example, the following verses are usually misquoted:
2:191-193, 2:216, 3:56, 3:151, 4:89, 5:33, 8:12, 8:39, 8:57, 9:5, 9:14, 9:29, 9:30, 9:73, 9:111, 9:123, 17:16, 25:52, 47:3-4, 48:17, 48:29, 61:4, 66:9.
to represent Islam as extremist.
However, the footnotes on these verses are well-done and telling the true context behind them.
As Allah (SWT) says:
"Exalted is Allah, the True King! Do not rush to recite ˹a revelation of˺ the Quran ˹O Prophet˺ before it is ˹properly˺ conveyed to you, and pray, “My Lord! Increase me in knowledge.”" 20:114
which basically means to not rush, indirectly means (for us) to read FULL information with context and not judge the verses directly.
Allah knows best, and may He delete this if I am misunderstanding, aameen.
JazakAllah.

**Comment by MahmoudiRamly** [comment]
@Haxsen Thanks for considering this.
With all due respect, Whoever wants to misquote would ignore all context and historical explanations and even following verses.

One example I have seen in a video someone quoting [`animosity and hatred forever`](https://quran.com/60:4) and ignoring [`dealing kindly and fairly`](https://quran.com/60:8) in the next page/ After 4 verses.

We were already told about those:
[As for those in whose hearts is deviation [from truth], they will follow that of it which is unspecific, seeking discord and seeking an interpretation [suitable to them]](https://quran.com/2:7)

One other issue with footnotes is that it is bound to the specific printed translation being used for example your first example [2:191-193](https://quran.com/2:191-193) in `— Dr. Mustafa Khattab, the Clear Quran` translation:

>Kill them wherever you come upon them1 and drive them out of the places from which they have driven you out. For persecution2 is far worse than killing. And do not fight them at the Sacred Mosque unless they attack you there. If they do so, then fight them—that is the reward of the disbelievers.

Footnote

> This is probably the most misquoted verse from the Quran. To properly understand the verse, we need to put it into context. Misquoting verses and taking them out of context can be applied to any scripture. For example, in the Bible, Jesus says, “Do not think that I came to bring peace on earth. I did not come to bring peace but a sword!” (Matthew [10:34](https://quran.com/10:34)). He also says, “But as for these enemies of mine who did not want me to be their king—bring them here and slaughter them in my presence!” (Luke [19:27](https://quran.com/19:27)). And Moses says, “The Lord is a man of war, the Lord is his name.” (Exodus [15:3](https://quran.com/15:3)). For more details, see the Introduction.


Numbers referring to the Bible where automatically linked to Quran verses, which is obviously not intended.

Also not sure how to `see the Introduction.`

I am not against explanation and clarifying context, I am only suggesting to keep the Quranic text pure from translator comments in the main Quran.com , and If possible introduce a separate subdomain/site for elaboration and commentary where it would be more clear that it is a human explanation.

Sorry If I did not fully translate my Arabic text but what prompted me to open this issue was `— Tafheem-ul-Quran - Abul Ala Maududi` translator foot note on [22:46](https://quran.com/22:46) describing the verse as a metaphor while [new scientific discoveries](https://www.youtube.com/watch?v=LelkiUDS0yM) proved it is [literal by the creator](https://www.youtube.com/watch?v=nzlas7rljUw).

I hope I made my point clear, And May Allah guide us to what is best to convey his last book.

**Comment by Haxsen** [comment]
> Numbers referring to the Bible where automatically linked to Quran verses, which is obviously not intended.

True, it is probably the fault of who added these specific footnotes and weblinked the verses while they shouldn't be interactable.
> Also not sure how to `see the Introduction`.

True that is not helping at all. Again the fault of contributor.

And to be honest about [22:46](https://quran.com/22:46) it's either way right if you take it literal or metaphor because the output is same: Heart contains the center of emotions. (atleast to me)

But disregarding footnotes as a whole isn't very good idea.

**Comment by MahmoudiRamly** [comment]
[`Have they not journeyed in the land that their hearts might understand and their ears might listen? For indeed it is not the eyes that are blinded;1 it is rather the hearts in the breasts that are rendered blind.`](https://quran.com/22:46)
`— Tafheem-ul-Quran - Abul Ala Maududi`
`Footnote
The words “blinded are the hearts” have been used in the metaphorical and not in the literal sense. Since the heart is regarded as the center of emotions, feelings and of mental and moral qualities, these words have been used to imply that their obduracy has inhibited them from feeling and acting rationally.`

I think the translator (may Allah have mercy on him) does not agree that `metaphorical` == `literal`:
`The words “blinded are the hearts” have been used in the metaphorical and not in the literal sense.`

When `X` is not `Y` then `X!=Y`

The [translator](https://en.wikipedia.org/wiki/Abul_A%27la_Maududi) who passed away on 1979  (may Allah have mercy on him), wrote that foot note to the best of his knowledge at the time he lived, and we assume he meant good.

It is understood that translation does not convey the full meaning due to the richness of Arabic Language, and I am certain that the translators (May Allah reward them all) have done their best to accurately translate to the best of their abilities.

The suggestion is aiming to seek highest accuracy in conveying the verses meaning, including foot notes that may have discrepancies due to the fact they are comments written by fallible humans, Causes confusion to the reader who is seeking an accurate translation.

In a pure Arabic Mushaf you would not find a note saying 
>Intoxicants were prohibited in the Quran in three stages: [2:219](https://quran.com/2:219), [4:43](https://quran.com/4:43), and finally [5:90-91](https://quran.com/5:90-91).

Or containing some bible verses and that is the aim to make the main Quran.com pure like an Arabic Mushaf with no human comments, Just a translation of meanings seeking accuracy.

Of course we do have a massive heritage of elaboration and commentary books which are very important but the aim here to draw a clear line between Allah's words meanings translation and human comments, and that would be by having separate website for such purpose.
This has been already done in [AlMakataba ALShamlah](https://shamela.ws/) but no online version with the same functionality.
![](https://old.shamela.ws/files/help/imgs/quran-tafseer/moqarana.png)

And Allah knows best,

هذا والله من وراء القصد والله أعلى وأعلم

**Comment by mustafa0x** [comment]
The footnote isn't necessarily fully accurate (what does it even mean for the heart to be literally blind?) but it's also not clearly incorrect. I don't see it necessary to remove anything.

> these words have been used to imply that their obduracy has inhibited them from feeling and acting rationally

The phrasing is clunky (feeling rationally is a bit of a paradox) but it is correct.

قال تعالى: أَفَلَمۡ یَسِیرُوا۟ فِی ٱلۡأَرۡضِ فَتَكُونَ لَهُمۡ قُلُوبࣱ **یَعۡقِلُونَ** بِهَاۤ

So blinding is referring to the ability to reason. The Qur'an addresses the Arabs first, not us, that might have a different perspective on reality due to a new discovery.

**Comment by ahmedre** [comment]
جزاكم الله خيراً
closing for now

**Comment by mustafa0x** [comment]
> This has been already done in [AlMakataba ALShamlah](https://shamela.ws/) but no online version with the same functionality.

See https://tafsir.app and https://app.turath.io, they should be good alternatives.
